["workspace"]
members = ["domain", "usecase", "application", "common/*", "in_memory_persistence"]

[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "rust_hex_sandbox"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
structmap = "0.1.6"
structmap-derive = "0.1.6"

domain = { path = "./domain" }
usecase = { path = "./usecase" }
in_memory_persistence = { path = "./in_memory_persistence" }
common_types = { path = "./common/types" }
common_events = { path = "./common/events" }