[package]
name = "in_memory_persistence"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
common = { path = "../common" }
domain = { path = "../domain" }
usecase = { path = "../usecase" }

