[package]
name = "in_memory_persistence"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new = "0.5.9"
serde = { version = "1.0.162", features = ["derive","rc","alloc"] }
serde_derive = "1.0.162"
erased-serde = "0.3.25"

common_types = { path = "../common/types" }
common_events = { path = "../common/events" }
domain = { path = "../domain" }
usecase = { path = "../usecase" }

