[package]
name = "common_types"
version.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive-new.workspace = true
time.workspace = true
serde.workspace = true
serde_derive.workspace = true
erased-serde.workspace = true
derivative.workspace = true
enum_dispatch.workspace = true
enum_access.workspace = true
thiserror.workspace = true


[dependencies.uuid]
version = "1.3.2"
features = [
    "v4", # Lets you generate random UUIDs
    "fast-rng", # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time
    "serde"
]